- MBTI/src/main/java/com/mbti/MBTI/testController.java
> #1 로그인페이구현

- MBTI/src/main/frontend/src/Login/FindPassword.js
- MBTI/src/main/frontend/src/Login/LoginPage.js
- MBTI/src/main/frontend/src/css/question/question.css
- MBTI/src/main/frontend/src/startTest/TestStart.js
- MBTI/src/main/frontend/src/test/testHeader.css
> 61-mainpage

- MBTI/src/main/frontend/src/App.js
- MBTI/src/main/frontend/src/DetailApp/Mbtiintrodusion.js
- MBTI/src/main/frontend/src/board/BoardMain.js
- MBTI/src/main/frontend/src/board/css/board.css
- MBTI/src/main/frontend/src/main/Header.js
- MBTI/src/main/frontend/src/profiles/components/TypeGroup.js
- MBTI/src/main/frontend/src/profiles/components/TypeGroupComponent.js
- MBTI/src/main/frontend/src/profiles/components/data.json
- MBTI/src/main/frontend/src/profiles/css/typeGroup.css
> fixed navigate & JSON data

- MBTI/src/main/frontend/src/App.js
> 75 앱js 에러수정

- MBTI/src/main/frontend/src/App.js
- MBTI/src/main/frontend/src/css/myPage/userInfo.css
- MBTI/src/main/frontend/src/css/signup/signup.css
- MBTI/src/main/frontend/src/css/test/result.css
- MBTI/src/main/frontend/src/resultpage/ResultPage.js
- MBTI/src/main/frontend/src/test/testResult.css
> 77-결과페이지UI구현

- MBTI/src/main/frontend/src/DetailApp/Detailpage/Introduction.js
- MBTI/src/main/frontend/src/DetailApp/MbtiRelationships.js
- MBTI/src/main/frontend/src/DetailApp/MbtiSW.js
- MBTI/src/main/frontend/src/DetailApp/Mbticareerpaths.js
- MBTI/src/main/frontend/src/DetailApp/Mbticonclusion.js
- MBTI/src/main/frontend/src/DetailApp/Mbtifriendship.js
- MBTI/src/main/frontend/src/DetailApp/Mbtiintrodusion.js
- MBTI/src/main/frontend/src/DetailApp/Mbtiparenthood.js
- MBTI/src/main/frontend/src/DetailApp/Mbtiworkplacehabits.js
- MBTI/src/main/frontend/src/DetailApp/SidevarLeft.js
- MBTI/src/main/frontend/src/DetailApp/SocialIcons.js
- MBTI/src/main/frontend/src/css/detail/detatil.css
> 79 디테일 페이지 버튼페이지이동,css수정

- MBTI/src/main/frontend/src/DetailApp/MbtiRelationships.js
- MBTI/src/main/frontend/src/DetailApp/MbtiSW.js
- MBTI/src/main/frontend/src/DetailApp/Mbticareerpaths.js
- MBTI/src/main/frontend/src/DetailApp/Mbticonclusion.js
- MBTI/src/main/frontend/src/DetailApp/Mbtifriendship.js
- MBTI/src/main/frontend/src/DetailApp/Mbtiintrodusion.js
- MBTI/src/main/frontend/src/DetailApp/Mbtiparenthood.js
- MBTI/src/main/frontend/src/DetailApp/Mbtiworkplacehabits.js
> 93 디테일페이지 css에러 수정

- MBTI/src/main/frontend/src/DetailApp/Mbtiintrodusion.js
- MBTI/src/main/frontend/src/DetailApp/db/introduciondata.js
- MBTI/src/main/frontend/src/resultpage/ResultMain.js
- MBTI/src/main/frontend/src/resultpage/ResultPage.js
- MBTI/src/main/frontend/src/startTest/TestStart.js
> 98 결과페이지랑 상세페이지연결

- MBTI/src/main/frontend/src/myPage/UserInformation.js
- MBTI/src/main/frontend/src/sign/Signup.js
- MBTI/src/main/java/user/controller/UserController.java
- MBTI/src/main/java/user/service/UserService.java
- MBTI/src/main/java/user/service/UserServiceImpl.java
> 106-이메일 중복 확인중 & 리액트 오류 확인

- MBTI/build.gradle
- MBTI/src/main/frontend/package.json
- MBTI/src/main/frontend/src/css/signup/signup.css
- MBTI/src/main/frontend/src/sign/Signup.js
- MBTI/src/main/java/com/mbti/MBTI/user/controller/UserController.java
- MBTI/src/main/resources/mapper/userMapper.xml
> 132-회원가입유효성완료

- MBTI/src/main/frontend/src/sign/Signup.js
> 138-회원가입페이지오류수정

- MBTI/src/main/frontend/src/resultpage/ResultMain.js
- MBTI/src/main/frontend/src/resultpage/ResultPage.js
> 140_resultpage_con_bumjoo

- MBTI/src/main/frontend/package.json
- MBTI/src/main/frontend/src/css/myPage/userInfo.css
- MBTI/src/main/frontend/src/myPage/UserInformation.js
- MBTI/src/main/frontend/src/sign/Signup.js
- MBTI/src/main/frontend/src/test/Test.js
- MBTI/src/main/frontend/yarn.lock
- MBTI/src/main/java/com/mbti/MBTI/user/controller/UserController.java
- MBTI/src/main/java/com/mbti/MBTI/user/dao/UserDAO.java
- MBTI/src/main/java/com/mbti/MBTI/user/dao/UserDAOMyBatis.java
- MBTI/src/main/java/com/mbti/MBTI/user/service/UserService.java
- MBTI/src/main/java/com/mbti/MBTI/user/service/UserServiceImpl.java
- MBTI/src/main/resources/mapper/userMapper.xml
> 142-회원가입완성 유저페이지수정중

- MBTI/src/main/frontend/src/App.js
- MBTI/src/main/frontend/src/Login/LoginPage.js
- MBTI/src/main/frontend/src/Login/LoginPageMain.js
- MBTI/src/main/frontend/src/board/FreeBoard.js
- MBTI/src/main/frontend/src/board/boardList/components/BoardWarp.js
- MBTI/src/main/frontend/src/board/boardWrite/FreeBoardWrite.js
- MBTI/src/main/frontend/src/css/main/header.css
- MBTI/src/main/frontend/src/main/Header.js
- MBTI/src/main/frontend/src/main/Header2.js
- MBTI/src/main/frontend/src/sign/Signup.js
> 144-boardwrite

- MBTI/src/main/java/com/mbti/MBTI/FreeComment/bean/FreeCommentDTO.java
- MBTI/src/main/java/com/mbti/MBTI/FreeComment/controller/FreeCommentController.java
- MBTI/src/main/java/com/mbti/MBTI/FreeComment/dao/FreeCommentDAO.java
- MBTI/src/main/java/com/mbti/MBTI/FreeComment/dao/FreeCommentDAOMyBatis.java
- MBTI/src/main/java/com/mbti/MBTI/FreeComment/service/FreeCommentService.java
- MBTI/src/main/java/com/mbti/MBTI/FreeComment/service/FreeCommentServiceImpl.java
- MBTI/src/main/resources/application.properties
- MBTI/src/main/resources/mapper/commentMapper.xml
- MBTI/src/main/resources/mybatis-config.xml
146_FreeComment_springboot_bumjoo
> 146_FreeComment_springboot_bumjoo

- MBTI/src/main/frontend/src/myPage/UserInformation.js
> 153-회원정보 수정 구현

- MBTI/src/main/frontend/package-lock.json
- MBTI/src/main/frontend/package.json
- MBTI/src/main/frontend/src/Login/LoginPage.js
- MBTI/src/main/frontend/src/board/boardWrite/FreeBoardWrite.js
- MBTI/src/main/frontend/src/board/css/FreeBoardWrite.css
- MBTI/src/main/frontend/yarn.lock
- MBTI/src/main/java/com/mbti/MBTI/freeboard/controller/FreeBoardController.java
- MBTI/src/main/java/com/mbti/MBTI/freeboard/dao/FreeBoardDAO.java
- MBTI/src/main/java/com/mbti/MBTI/freeboard/dao/FreeBoardDAOMyBatis.java
- MBTI/src/main/java/com/mbti/MBTI/freeboard/sevice/FreeBoardService.java
- MBTI/src/main/java/com/mbti/MBTI/freeboard/sevice/FreeBoardServiceImpl.java
- MBTI/src/main/resources/mapper/freeboardMapper.xml
> 157-freeboardwriteform

- MBTI/src/main/frontend/src/App.js
- MBTI/src/main/frontend/src/replyboard/ReplyBoard.js
- MBTI/src/main/frontend/src/replyboard/css/ReplyBoard.css
- MBTI/src/main/java/com/mbti/MBTI/FreeComment/bean/FreeCommentDTO.java
- MBTI/src/main/java/com/mbti/MBTI/FreeComment/controller/FreeCommentController.java
- MBTI/src/main/java/com/mbti/MBTI/FreeComment/dao/FreeCommentDAO.java
- MBTI/src/main/java/com/mbti/MBTI/FreeComment/dao/FreeCommentDAOMyBatis.java
- MBTI/src/main/java/com/mbti/MBTI/FreeComment/service/FreeCommentService.java
- MBTI/src/main/java/com/mbti/MBTI/FreeComment/service/FreeCommentServiceImpl.java
- MBTI/src/main/java/com/mbti/MBTI/freeboard/controller/FreeBoardController.java
- MBTI/src/main/resources/mapper/commentMapper.xml
> 160 reply comment bumjoo

- MBTI/src/main/frontend/package.json
- MBTI/src/main/frontend/src/App.js
- MBTI/src/main/frontend/src/Login/LoginPage.js
- MBTI/src/main/frontend/src/board/boardWrite/CKeditor.js
- MBTI/src/main/frontend/src/board/boardWrite/FreeBoardWrite.js
- MBTI/src/main/frontend/src/board/boardWrite/MbtiBoardWrite.js
- MBTI/src/main/frontend/src/board/css/FreeBoardWrite.css
- MBTI/src/main/frontend/yarn.lock
- MBTI/src/main/java/com/mbti/MBTI/freeboard/controller/FreeBoardController.java
> 164-freeboardwrite

- MBTI/src/main/frontend/package-lock.json
- MBTI/src/main/frontend/src/board/boardView/FreeBoardView.js
- MBTI/src/main/frontend/src/board/boardView/MbtiBoardView.js
- MBTI/src/main/frontend/src/board/boardView/MbtiBoardViewMain.js
- MBTI/src/main/frontend/src/replyboard/MbtiReplyBoard.js
- MBTI/src/main/frontend/src/replyboard/ReplyBoard.js
- MBTI/src/main/frontend/src/replyboard/css/ReplyBoard.css
- MBTI/src/main/frontend/yarn.lock
- MBTI/src/main/java/com/mbti/MBTI/FreeComment/controller/FreeCommentController.java
- MBTI/src/main/java/com/mbti/MBTI/board/bean/FreeBoardDTO.java
- MBTI/src/main/java/com/mbti/MBTI/freeboard/bean/FreeBoardDTO.java
- MBTI/src/main/resources/mapper/commentMapper.xml
> 206 replydata con css bumjoo

- MBTI/src/main/frontend/src/replyboard/css/ReplyBoard.css
> 209 reply css bumjoo

- MBTI/src/main/frontend/src/board/boardView/FreeBoardView.js
- MBTI/src/main/frontend/src/myPage/ModalDelete.js
- MBTI/src/main/frontend/src/myPage/ModalUserInfo.js
- MBTI/src/main/frontend/src/myPage/MymbtiResult.js
- MBTI/src/main/frontend/src/myPage/Mypage.js
- MBTI/src/main/frontend/src/myPage/UserInformation.js
- MBTI/src/main/frontend/src/resultpage/ResultMain.js
- MBTI/src/main/frontend/src/resultpage/ResultPage.js
- MBTI/src/main/frontend/src/sign/Signup.js
- MBTI/src/main/java/com/mbti/MBTI/freeboard/controller/FreeBoardController.java
- MBTI/src/main/java/com/mbti/MBTI/freeboard/dao/FreeBoardDAO.java
- MBTI/src/main/java/com/mbti/MBTI/freeboard/dao/FreeBoardDAOMyBatis.java
- MBTI/src/main/java/com/mbti/MBTI/freeboard/sevice/FreeBoardService.java
- MBTI/src/main/java/com/mbti/MBTI/freeboard/sevice/FreeBoardServiceImpl.java
- MBTI/src/main/java/com/mbti/MBTI/user/controller/UserController.java
- MBTI/src/main/resources/mapper/freeboardMapper.xml
> 211-좋아요기능 구현
